---
- name: Pull Docker Image and Run Container
  hosts: localhost
  remote_user: naval1
  become: false
  tasks:
    - name: Stop and Remove Existing sinc_calc Container (if exists)
      shell: |
        docker stop sinc_calc || true
        docker rm sinc_calc || true
      ignore_errors: yes

    - name: Remove Existing Docker Image (if exists)
      shell: docker rmi -f navalbisht444/test || true
      ignore_errors: yes

    - name: Pull Docker Image from Docker Hub
      docker_image:
        name: "navalbisht444/test"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Run sinc_calc Container
      shell: docker run -it -d --name sinc_calc navalbisht444/test /bin/bash

